# todo: separate ssh and wireguard services from rtorrent-rutorrent
services:
    wireguard-client:
        image: lscr.io/linuxserver/wireguard:latest
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./config:/config
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        healthcheck:
            test: "ping -w 5 -c 1 -q 10.13.13.1 > /dev/null" # todo: dynamic ip
            interval: 10s
            retries: 5
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            autoheal: true
        ports:
            - target: ${RUTORRENT_PORT}
              published: ${RUTORRENT_PORT}
              protocol: tcp

    ssh-client:
        user: "1000:0"
        build:
            context: .
            dockerfile: ./Dockerfile-ssh-client
        command: ["autossh", "-M", "0", "-T", "-N", "-4", "pbktunnel"]
        volumes:
            - .ssh:/home/appuser/.ssh:ro
        restart: unless-stopped
        network_mode: "service:wireguard-client"
        depends_on:
            wireguard-client:
                condition: service_healthy
        healthcheck:
            test: "ssh -q -o BatchMode=yes  -o StrictHostKeyChecking=no -o ConnectTimeout=5 -o ClearAllForwardings=yes pbktunnel 'exit 0'"
            interval: 1m
            retries: 5
        labels:
            autoheal: true

    rtorrent-rutorrent:
        image: crazymax/rtorrent-rutorrent:latest
        env_file:
            - "rtorrent/rtorrent-rutorrent.env"
            - ".env"
        entrypoint:
            - "/bin/bash"
            - "-c"
            - "echo \"Checking workdir...\"; until [ -f /downloads/.mounted ]; do echo \"Waiting for workdir to be available...\"; sleep 5; done; echo \"Workdir is available, starting...\"; ./init"
        volumes:
            - "./rtorrent/data:/data"
        ulimits:
            nproc: 65535
            nofile:
                soft: 32000
                hard: 40000
        restart: unless-stopped
        network_mode: "service:wireguard-client"
        depends_on:
            - wireguard-client

    rtorrent-logs:
        image: bash
        command: bash -c 'tail -f /log/*.log'
        depends_on:
            - rtorrent-rutorrent
        volumes:
            - "./rtorrent/data/rtorrent/log:/log"
        restart: always

    autoheal:
        image: willfarrell/autoheal:latest
        tty: true
        container_name: autoheal
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            AUTOHEAL_INTERVAL: 60
            AUTOHEAL_START_PERIOD: 60
            # WEBHOOK_URL: "" # todo: telegram message
networks:
    default:
        name: paha-gaming-ssh-forwarding
