version: "3.7"
services:
    wireguard-client:
        image: lscr.io/linuxserver/wireguard:latest
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./config:/config
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        healthcheck:
            test: "exit 0" # todo: check server connection
        extra_hosts:
            - "host.docker.internal:host-gateway"
    ssh-client:
        user: "1000:0"
        build:
            context: .
            dockerfile: ./Dockerfile-ssh-client
        command: ["autossh", "-M", "0", "-T", "-N", "-4", "pbktunnel"]
        environment:
            SSH_AUTH_SOCK: /ssh-agent/ssh-agent.sock
        volumes:
            - ssh-agent:/ssh-agent
            - .ssh:/home/appuser/.ssh:ro
        restart: unless-stopped
        network_mode: "service:wireguard-client"
        depends_on:
            wireguard-client:
                condition: service_healthy
volumes:
    ssh-agent:
        external: true
networks:
    default:
        name: paha-gaming-ssh-forwarding
